### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by kennynaoh** [JasonSanford/leaflet-vector-layers#63]
Hello @JasonSanford ,
I am the member of the [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
Which [license](https://github.com/cdnjs/cdnjs/blob/master/tools/license-list.json) do you use?
Thanks.

https://github.com/cdnjs/cdnjs/issues/6746

**Comment by glenrobertson** [comment]
Looks like BSD to me

**Comment by kennynaoh** [comment]
What's the detail about BSD?
Reference this [license](https://github.com/cdnjs/cdnjs/blob/master/tools/license-list.json).
Thanks.

**Comment by JasonSanford** [comment]
I think it's this one. https://github.com/cdnjs/cdnjs/blob/master/tools/license-list.json#L34

**Comment by kennynaoh** [comment]
Thanks.
